# production environment
FROM nginx:stable-alpine
COPY --from=web_front /app/build /usr/share/nginx/html
# new
COPY nginx/nginx-test.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
