version: "3.8"
services: 
  mongodb:
    image: 'mongo'
    hostname: "admintools.online"
    container_name: "mongodb"
    volumes: 
      - mongodata:/data/db
      - keyfile:/keyfile
    ports: 
      - 27017:27017
    entrypoint: ["mongod", "--bind_ip_all", "--noscripting", "--auth", "--keyFile", "/keyfile/mongodb.keyfile", "--replSet", "rs0"]
  web_front:
    image: 'web_front'
    container_name: 'web_front'
    build:
      context: ./appraisal-web-front
      dockerfile: ../configs/production/Dockerfile.web_front
  connect:
    image: 'connect'
    container_name: 'connect'
    build:
      context: './admintools-connect'
      dockerfile: '../configs/local/Dockerfile.connect'
    ports:
      - 3004:3004
  auth:
    image: 'auth'
    container_name: 'auth'
    build:
      context: ./admintools-auth
      dockerfile: ../configs/local/Dockerfile.auth
    ports: 
      - 3003:3003
  redis:
    image: redis:alpine
    container_name: redis
    env_file: .env
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379
  nginx:
    image: 'nginx'
    container_name: 'nginx'
    build:
      context: ./configs
      dockerfile: ./production/Dockerfile.nginx
    volumes: 
      - webroot:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    ports: 
      - 80:80
      - 443:443
    depends_on:
      - web_front
  web_back:
    image: 'web_back'
    container_name: 'web_back'
    build:
      context: ./appraisal-web-back
      dockerfile: ../configs/production/Dockerfile.web_back
    ports:
      - 3001:3001
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on: 
      - web_front
    command: certonly --webroot --webroot-path=/var/www/html --email andrei.dimitrascu.94@gmail.com --agree-tos --no-eff-email -d admintools.online,www.admintools.online

volumes: 
  mongodata:
  certbot-etc:
  certbot-var:
  webroot:
    driver: local
    driver_opts:
      type: none
      device: /home/data/views
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /appraisal-web-base/dhparam/
      o: bind
  keyfile:
    driver: local
    driver_opts:
      type: none
      device: /appraisal-web-base/keyfile/
      o: bind
