version: "3.8"
services: 
  web_front_test:
    image: 'web_front_test'
    container_name: 'web_front_test'
    build:
      context: ./appraisal-web-front
      dockerfile: Dockerfile.test
    volumes: 
      - webroot:/usr/share/nginx/html2
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
  web_back_test:
    image: 'web_back_test'
    container_name: 'web_back_test'
    build: ./appraisal-web-back
    ports:
      - 3001:3001

volumes: 
  mongodata:
  certbot-etc:
  certbot-var:
  webroot:
    driver: local
    driver_opts:
      type: none
      device: /home/data/views
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /appraisal-web-base/dhparam/
      o: bind
  keyfile:
    driver: local
    driver_opts:
      type: none
      device: /appraisal-web-base/keyfile/
      o: bind
