version: "3.8"
services: 
  # Mongo 3 node-replica set
  mongodb1:
    image: 'mongo'
    hostname: "mongodb1"
    container_name: "mongodb1"
    volumes: 
      - mongodata:/data/db
    ports: 
      - 27017:27017
    env_file: .env 
    extra_hosts: 
      - "mongodb:${MONGODB}"
    entrypoint: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
  web_front:
    image: 'web_front:dev'
    container_name: 'web_front'
    environment: 
      - CI=true
      - HOST=web_front
    build:
      context: ./appraisal-web-front
      dockerfile: ../configs/local/Dockerfile.dev_front
    ports: 
      - 3000:3000
    volumes: 
      - ./appraisal-web-front:/app
  web_back:
    image: 'web_back:dev'
    container_name: 'web_back'
    build:
      context: ./appraisal-web-back
      dockerfile: ../configs/local/Dockerfile.dev_back
    volumes: 
      - ./appraisal-web-back:/urs/src/appraisal-back
    env_file: .env 
    extra_hosts: 
      - "mongodb:${MONGODB}"
    ports:
      - 3001:3001
  nginx_dev:
    image: 'nignx_dev'
    container_name: 'nginx_dev'
    build: 
      context: ./configs
      dockerfile: ./local/Dockerfile-nginx.dev
    ports:
    - 3002:3002
volumes: 
  mongodata:
