version: "3.8"
services: 
  mongodb:
    image: 'mongo'
    container_name: "mongodb"
    volumes: 
      - mongodata:/data/db
    ports: 
      - 27017:27017
  web_front:
    image: 'web_front'
    container_name: 'web_front'
    build: ./appraisal-web-front
    ports: 
      - 80:80
  web_back:
    image: 'web_back'
    container_name: 'web_back'
    build: ./appraisal-web-back
    environment: 
      - MONGODB_URI=mongodb://mongodb:27017/appraisalDB
      - redirectUrl=http://localhost/api/auth/openid/return
    ports:
      - 3001:3001

volumes: 
  mongodata:
  